"""
Topology loader - parse astra-sim topology files into in-memory graph.

Supports topology files generated by gen_Topo_Template.py (Spectrum-X,
AlibabaHPN, DCN+ formats).

File format:
  Line 1: total_nodes gpu_count nv_switch_count other_switch_count total_links gpu_type
  Line 2: switch_node_ids (space-separated)
  Line 3+: src dst bandwidth latency error_rate (each line = bidirectional link)
"""

import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional


class NodeType(str, Enum):
    """Type of network node."""

    GPU = "gpu"
    NV_SWITCH = "nv_switch"  # NVLink switch
    ASW_SWITCH = "asw_switch"  # Aggregate switch
    PSW_SWITCH = "psw_switch"  # Pod switch
    DSW_SWITCH = "dsw_switch"  # Distribution switch


@dataclass
class Link:
    """
    Represents one direction of a physical link in the topology.

    Each line in the topology file represents a bidirectional link,
    which we model as two Link objects: (src→dst) and (dst→src),
    both sharing the same bandwidth/latency/error_rate.

    Link identification uses (src, dst) tuple as the key.
    """

    src: int
    dst: int
    bandwidth_gbps: float
    latency_us: float
    error_rate: float

    @property
    def link_id(self) -> tuple[int, int]:
        """Unique identifier for this link: (src, dst)."""
        return (self.src, self.dst)

    def __hash__(self):
        return hash((self.src, self.dst))

    def __eq__(self, other):
        if not isinstance(other, Link):
            return False
        return self.src == other.src and self.dst == other.dst


@dataclass
class NetworkTopology:
    """
    In-memory representation of the network topology.

    Provides graph traversal APIs for routing algorithms and
    link lookup for bandwidth/delay queries.
    """

    # All links indexed by (src, dst) tuple
    links: dict[tuple[int, int], Link] = field(default_factory=dict)

    # Adjacency list: node -> list of (neighbor, link)
    adjacency: dict[int, list[tuple[int, Link]]] = field(default_factory=dict)

    # Node type mapping: node_id -> type
    node_types: dict[int, NodeType] = field(default_factory=dict)

    # Metadata
    total_nodes: int = 0
    gpu_count: int = 0
    switch_count: int = 0
    gpu_type: str = ""

    # List of GPU node IDs for quick iteration
    gpu_nodes: list[int] = field(default_factory=list)

    # List of all switch node IDs
    switch_nodes: list[int] = field(default_factory=list)

    def add_link(self, link: Link):
        """Add a link and update adjacency list."""
        self.links[link.link_id] = link

        if link.src not in self.adjacency:
            self.adjacency[link.src] = []
        self.adjacency[link.src].append((link.dst, link))

        # Ensure dst node exists in adjacency (even if it has no outgoing edges yet)
        if link.dst not in self.adjacency:
            self.adjacency[link.dst] = []

    def get_link(self, src: int, dst: int) -> Optional[Link]:
        """Get link by (src, dst), or None if not found."""
        return self.links.get((src, dst))

    def get_neighbors(self, node: int) -> list[tuple[int, Link]]:
        """Get all outgoing neighbors of a node."""
        return self.adjacency.get(node, [])

    def get_gpu_nodes(self) -> list[int]:
        """Return list of all GPU node IDs."""
        return self.gpu_nodes

    def get_switch_nodes(self) -> list[int]:
        """Return list of all switch node IDs."""
        return self.switch_nodes

    def is_gpu_node(self, node: int) -> bool:
        """Check if a node is a GPU."""
        return node in self.gpu_nodes

    def is_switch_node(self, node: int) -> bool:
        """Check if a node is a switch."""
        return node in self.switch_nodes


class TopologyLoader:
    """Load and parse astra-sim topology files."""

    def load(self, topo_file: str | Path) -> NetworkTopology:
        """
        Parse topology file and build NetworkTopology.

        Args:
            topo_file: Path to topology file (astra-sim format)

        Returns:
            Populated NetworkTopology object

        Raises:
            FileNotFoundError: If topo_file doesn't exist
            ValueError: If file format is invalid
        """
        path = Path(topo_file)
        if not path.exists():
            raise FileNotFoundError(f"Topology file not found: {topo_file}")

        topo = NetworkTopology()

        with open(path, "r") as f:
            lines = [line.strip() for line in f if line.strip()]

        if len(lines) < 2:
            raise ValueError("Invalid topology file: missing header lines")

        # Parse first line: metadata
        # Note: header field 2 is "gpus_per_server", not total GPU count.
        # Actual GPU count = total_nodes - (nv_switch_count + other_switch_count)
        total_nodes, gpus_per_server, nv_switch_count, \
            other_switch_count, total_links, topo.gpu_type = self._parse_header(lines[0])

        topo.total_nodes = total_nodes
        topo.switch_count = nv_switch_count + other_switch_count
        topo.gpu_count = total_nodes - topo.switch_count

        # Parse second line: switch node IDs
        switch_ids = list(map(int, lines[1].split()))
        switch_set = set(switch_ids)

        # GPU nodes = all non-switch nodes
        gpu_nodes_set = set(range(total_nodes)) - switch_set

        topo.gpu_nodes = sorted(gpu_nodes_set)
        topo.switch_nodes = sorted(switch_set)

        # Assign node types
        for node_id in topo.gpu_nodes:
            topo.node_types[node_id] = NodeType.GPU

        # Classify switches: first nv_switch_count are NV switches, rest are network switches
        for i, sid in enumerate(switch_ids):
            if i < nv_switch_count:
                topo.node_types[sid] = NodeType.NV_SWITCH
            elif i < nv_switch_count + other_switch_count:
                topo.node_types[sid] = NodeType.ASW_SWITCH

        # Parse link definitions (lines 3+)
        # Each line in the topology file represents a bidirectional link.
        # We create both (src→dst) and (dst→src) Link objects with the same
        # bandwidth/latency/error_rate, matching the NS-3 behavior where
        # qbb.Install(snode, dnode) creates a bidirectional channel.
        for line in lines[2:]:
            link = self._parse_link_line(line)
            if link:
                topo.add_link(link)
                # Add reverse link (same properties, opposite direction)
                reverse = Link(
                    src=link.dst,
                    dst=link.src,
                    bandwidth_gbps=link.bandwidth_gbps,
                    latency_us=link.latency_us,
                    error_rate=link.error_rate,
                )
                topo.add_link(reverse)

        return topo

    def _parse_header(self, line: str) -> tuple[int, int, int, int, int, str]:
        """Parse first line of topology file."""
        parts = line.split()
        if len(parts) < 6:
            raise ValueError(f"Invalid header line: {line}")

        return (
            int(parts[0]),  # total_nodes
            int(parts[1]),  # gpu_count
            int(parts[2]),  # nv_switch_count
            int(parts[3]),  # other_switch_count
            int(parts[4]),  # total_links
            parts[5],  # gpu_type
        )

    def _parse_link_line(self, line: str) -> Optional[Link]:
        """Parse a link definition line."""
        parts = line.split()
        if len(parts) < 5:
            return None

        try:
            src = int(parts[0])
            dst = int(parts[1])
            bandwidth = self._parse_bandwidth(parts[2])
            latency = self._parse_latency(parts[3])
            error_rate = float(parts[4])

            return Link(
                src=src,
                dst=dst,
                bandwidth_gbps=bandwidth,
                latency_us=latency,
                error_rate=error_rate,
            )
        except (ValueError, IndexError) as e:
            raise ValueError(f"Invalid link line: {line} ({e})")

    def _parse_bandwidth(self, bw_str: str) -> float:
        """Parse bandwidth string like '400Gbps' or '2880Gbps' to float (Gbps)."""
        match = re.match(r"([\d.]+)\s*(Gbps|Mbps|Tbps)", bw_str, re.IGNORECASE)
        if not match:
            raise ValueError(f"Invalid bandwidth format: {bw_str}")

        value = float(match.group(1))
        unit = match.group(2).upper()

        if unit == "MBPS":
            return value / 1000.0
        elif unit == "TBPS":
            return value * 1000.0
        else:  # GBPS
            return value

    def _parse_latency(self, lat_str: str) -> float:
        """Parse latency string like '0.0005ms' or '25us' to float (microseconds)."""
        match = re.match(r"([\d.]+)\s*(ms|us|ns|s)", lat_str, re.IGNORECASE)
        if not match:
            raise ValueError(f"Invalid latency format: {lat_str}")

        value = float(match.group(1))
        unit = match.group(2).lower()

        if unit == "s":
            return value * 1e6
        elif unit == "ms":
            return value * 1e3
        elif unit == "ns":
            return value / 1e3
        else:  # us
            return value
